const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
Promise.all([
  'federal-parliamentary-players.json','party-rosters.json','state-territory-parliamentary-players.json','queensland-parliamentary-players.json','western-australia-parliamentary-players.json','new-south-wales-parliamentary-players.json','victoria-parliamentary-players.json','political-competitions.json'
].map(f=>fetch('data/runtime/'+f+'?'+Date.now(),{cache:'no-store'}).then(r=>r.json()))).then(([fed,fedRosters,st,qld,wa,nsw,vic,competitions])=>{
  const fedTeams=new Map((fedRosters.parties||[]).map(t=>[t.party_id,t.short_name]));
  const compactField=(data,label)=>{const ix=Object.fromEntries((data.player_fields||[]).map((f,i)=>[f,i]));const players=(data.players||[]).map(r=>{const abbr=r[ix.party_abbreviation],m=data.party_map?.[abbr]||{},chamber=ix.chamber==null?(data.chamber||'LEGISLATIVE_ASSEMBLY'):r[ix.chamber],electorate=r[ix.electorate];return{actor_id:r[ix.actor_id],name:r[ix.name],chamber,electorate,party_abbreviation:abbr,party_id:m.party_id??null,team_name:m.short_name||m.name||'Independent',role:chamber==='LEGISLATIVE_COUNCIL'?'Member of the Legislative Council':`Member for ${electorate}`,status:'ACTIVE'}});return{id:data.competition_id,label,players,teams:(data.teams||[]).map(t=>({party_id:t.party_id,name:t.short_name||t.name,player_count:t.player_count})),independents:data.counts.independents}};
  const fields=[
    {id:'AUS-FED',label:'Federal Finals',players:(fed.players||[]).map(p=>({...p,electorate:p.division,team_name:fedTeams.get(p.party_id)||'Independent'})),teams:(fedRosters.parties||[]).map(t=>({party_id:t.party_id,name:t.short_name,player_count:t.player_count})),independents:fed.counts.independents},
    compactField(nsw,'NSW'),compactField(vic,'Victoria'),compactField(qld,'Queensland'),compactField(wa,'Western Australia'),
    ...(st.jurisdictions||[]).map(j=>{const teamMap=new Map((j.teams||[]).map(t=>[t.party_id,t.name]));return{id:j.competition_id,label:j.jurisdiction==='Australian Capital Territory'?'ACT':j.jurisdiction,players:(j.players||[]).map(p=>({...p,team_name:teamMap.get(p.party_id)||'Independent'})),teams:j.teams||[],independents:j.counts.independents}})
  ];
  const order=['AUS-FED','AUS-NSW','AUS-VIC','AUS-QLD','AUS-WA','AUS-ACT','AUS-NT'];fields.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
  const jurisdiction=document.getElementById('player-jurisdiction'),search=document.getElementById('player-search'),team=document.getElementById('player-team'),chamber=document.getElementById('player-chamber'),host=document.getElementById('player-list');
  jurisdiction.innerHTML=fields.map(f=>`<option value="${esc(f.id)}">${esc(f.label)} · ${f.players.length} players</option>`).join('');const requested=new URLSearchParams(location.search).get('jurisdiction');if(fields.some(f=>f.id===requested))jurisdiction.value=requested;
  const draw=()=>{const field=fields.find(f=>f.id===jurisdiction.value)||fields[0],q=search.value.trim().toLowerCase(),tv=team.value,cv=chamber.value,visible=field.players.filter(p=>(!q||[p.name,p.role,p.electorate,p.team_name,p.chamber].some(v=>String(v||'').toLowerCase().includes(q)))&&(!tv||(tv==='INDEPENDENT'?!p.party_id:p.party_id===tv))&&(!cv||p.chamber===cv));document.getElementById('player-count').textContent=`${visible.length} of ${field.players.length} ${field.label} players shown`;host.innerHTML=visible.map(p=>`<article class="directory-row"><div><span class="player-label">PLAYER · ${esc(String(p.chamber||'').replaceAll('_',' '))}</span><b>${esc(p.name)}</b><small>${esc(p.role||'')}</small></div><div class="directory-meta"><strong>${esc(p.team_name)}</strong><span>${esc(p.electorate||p.state||'')}</span></div></article>`).join('')||'<div class="empty-state">No players match these filters.</div>';history.replaceState(null,'',`${location.pathname}?jurisdiction=${encodeURIComponent(field.id)}`)};
  const rebuild=()=>{const field=fields.find(f=>f.id===jurisdiction.value)||fields[0];team.innerHTML='<option value="">All teams + independents</option>'+field.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(t=>`<option value="${esc(t.party_id)}">${esc(t.name)} · ${t.player_count} players</option>`).join('')+`<option value="INDEPENDENT">Independent · ${field.independents} players</option>`;const chambers=[...new Set(field.players.map(p=>p.chamber).filter(Boolean))].sort();chamber.innerHTML='<option value="">All chambers</option>'+chambers.map(c=>`<option value="${esc(c)}">${esc(String(c).replaceAll('_',' '))}</option>`).join('');draw()};
  jurisdiction.addEventListener('change',rebuild);search.addEventListener('input',draw);team.addEventListener('change',draw);chamber.addEventListener('change',draw);const progress=competitions.ingestion_progress||{};document.getElementById('player-meta').textContent=`${fields.reduce((n,f)=>n+f.players.length,0)} parliamentary players ingested across Federal Finals and ${progress.state_territory_jurisdictions_with_complete_current_player_rosters||0} state/territory competitions · ${progress.remaining_jurisdictions?.length||0} state competitions still roster-pending · ${vic.snapshot_id}`;rebuild();
}).catch(()=>document.getElementById('player-list').innerHTML='<div class="empty-state">Parliamentary player feeds unavailable.</div>');
