const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words=s=>String(s??'UNKNOWN').replaceAll('_',' ');

async function loadTeamIntelligence(){
  const jurisdiction=document.getElementById('team-jurisdiction');
  const select=document.getElementById('team-select');
  const view=document.getElementById('team-view');
  if(!select||!view)return;
  try{
    const responses=await Promise.all([
      'party-rosters.json','team-player-form.json','team-squad-depth.json','state-territory-parliamentary-players.json','queensland-parliamentary-players.json','western-australia-parliamentary-players.json','new-south-wales-parliamentary-players.json','victoria-parliamentary-players.json','south-australia-parliamentary-players.json','tasmania-parliamentary-players.json','political-competitions.json'
    ].map(f=>fetch('data/runtime/'+f+'?'+Date.now(),{cache:'no-store'})));
    if(!responses.every(r=>r.ok))throw new Error('Roster runtime unavailable');
    const [roster,form,depth,state,qld,wa,nsw,vic,sa,tas,competitions]=await Promise.all(responses.map(r=>r.json()));
    const formByTeam=new Map((form.team_form||[]).map(x=>[x.party_id,x]));
    const depthByTeam=new Map((depth.teams||[]).map(x=>[x.party_id,x]));
    const baseline={form_state:'BASELINE_ESTABLISHING',trend:'UNRESOLVED',signals:[],contradictions:[]};
    const compactPlayers=data=>(data.players||[]).map(r=>{const ix=Object.fromEntries((data.player_fields||[]).map((f,i)=>[f,i]));const abbr=r[ix.party_abbreviation],m=data.party_map?.[abbr]||{},chamber=ix.chamber==null?(data.chamber||'LEGISLATIVE_ASSEMBLY'):r[ix.chamber],electorate=r[ix.electorate];return{actor_id:r[ix.actor_id],name:r[ix.name],chamber,electorate,party_id:m.party_id??null,party:m.name||'Independent',role:chamber==='LEGISLATIVE_COUNCIL'?'Member of the Legislative Council':`Member for ${electorate}`,status:'ACTIVE'}});
    const compactField=(data,label)=>{const players=compactPlayers(data);return{id:data.competition_id,label,level:data.level||'STATE',independents:data.counts.independents,chamber_model:data.chamber_model,teams:(data.teams||[]).map(t=>({...t,display_name:t.short_name||t.name,team_state:'ACTIVE_PARLIAMENTARY_TEAM',players:players.filter(p=>p.party_id===t.party_id),state:baseline,coverage:100}))}};
    const fields=[
      {id:'AUS-FED',label:'Federal Finals',level:'FEDERAL',independents:roster.counts.independents,chamber_model:'BICAMERAL',teams:(roster.parties||[]).map(t=>({...t,display_name:t.short_name,players:t.actors||[],state:formByTeam.get(t.party_id),coverage:depthByTeam.get(t.party_id)?.coverage_percent??100}))},
      compactField(nsw,'NSW'),compactField(vic,'Victoria'),compactField(qld,'Queensland'),compactField(wa,'Western Australia'),compactField(sa,'South Australia'),compactField(tas,'Tasmania'),
      ...(state.jurisdictions||[]).map(j=>({id:j.competition_id,label:j.jurisdiction==='Australian Capital Territory'?'ACT':j.jurisdiction,level:j.level,independents:j.counts.independents,chamber_model:j.chamber_model,teams:(j.teams||[]).map(t=>({...t,display_name:t.name,team_state:'ACTIVE_PARLIAMENTARY_TEAM',players:(j.players||[]).filter(p=>p.party_id===t.party_id),state:baseline,coverage:100}))}))
    ];
    const order=['AUS-FED','AUS-NSW','AUS-VIC','AUS-QLD','AUS-WA','AUS-SA','AUS-TAS','AUS-ACT','AUS-NT'];fields.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
    jurisdiction.innerHTML=fields.map(f=>`<option value="${esc(f.id)}">${esc(f.label)} · ${f.teams.length} teams</option>`).join('');
    const requestedJurisdiction=new URLSearchParams(location.search).get('jurisdiction');if(fields.some(f=>f.id===requestedJurisdiction))jurisdiction.value=requestedJurisdiction;
    const currentField=()=>fields.find(f=>f.id===(jurisdiction.value||'AUS-FED'))||fields[0];
    const populateTeams=()=>{const field=currentField(),teams=field.teams.slice().sort((a,b)=>a.display_name.localeCompare(b.display_name));select.innerHTML=teams.map(t=>`<option value="${esc(t.party_id)}">${esc(t.display_name)} · ${t.player_count??t.players.length} players</option>`).join('');const requested=new URLSearchParams(location.search).get('team');const hit=teams.find(t=>t.party_id===requested||t.display_name.toLowerCase()===String(requested||'').toLowerCase());if(hit)select.value=hit.party_id;render()};
    const render=()=>{const field=currentField(),party=field.teams.find(t=>t.party_id===select.value)||field.teams[0];if(!party){view.innerHTML='<div class="empty-state">No team records available for this competition.</div>';return}const players=(party.players||[]).slice().sort((a,b)=>a.name.localeCompare(b.name)),leader=players.find(a=>a.actor_id===party.leader_actor_id),stateRecord=party.state||baseline,total=Number(party.player_count??players.length),isFederal=field.id==='AUS-FED',bicameral=field.chamber_model==='BICAMERAL',hasHouseAssembly=players.some(p=>p.chamber==='HOUSE_OF_ASSEMBLY'),primary=isFederal?Number(party.house_players??players.filter(p=>p.chamber==='HOUSE').length):hasHouseAssembly?players.filter(p=>p.chamber==='HOUSE_OF_ASSEMBLY').length:players.filter(p=>p.chamber==='LEGISLATIVE_ASSEMBLY').length,secondary=isFederal?Number(party.senate_players??players.filter(p=>p.chamber==='SENATE').length):bicameral?players.filter(p=>p.chamber==='LEGISLATIVE_COUNCIL').length:field.independents,primaryLabel=isFederal?'HOUSE':hasHouseAssembly?'HOUSE OF ASSEMBLY':'LEGISLATIVE ASSEMBLY',secondaryLabel=isFederal?'SENATE':bicameral?'LEGISLATIVE COUNCIL':'STANDALONE INDEPENDENTS';
      view.innerHTML=`<article class="party-card team-focus"><div class="party-head"><div><span class="team-label">TEAM · ${esc(field.label)}</span><h2>${esc(party.display_name)}</h2><p class="party-full">${esc(party.name||party.display_name)}</p></div><span class="team-state">${esc(words(party.team_state||'ACTIVE_PARLIAMENTARY_TEAM'))}</span></div><div class="leader-strip"><b>Captain / leader</b><span>${leader?esc(leader.name):isFederal?'No parliamentary leader resolved in current roster':'Leadership link not yet resolved in this competition roster'}</span></div><div class="form-strip"><div><small>TOTAL PLAYERS</small><strong>${total}</strong></div><div><small>${primaryLabel}</small><strong>${primary}</strong></div><div><small>${secondaryLabel}</small><strong>${secondary}</strong></div><div><small>ROSTER INGESTION</small><strong>${party.coverage}% · COMPLETE</strong></div></div><div class="form-strip"><div><small>TEAM FORM</small><strong>${esc(words(stateRecord.form_state))}</strong></div><div><small>TREND</small><strong>${esc(stateRecord.trend||'UNRESOLVED')}</strong></div><div><small>LIVE SIGNALS</small><strong>${(stateRecord.signals||[]).length}</strong></div><div><small>CONTRADICTIONS</small><strong>${(stateRecord.contradictions||[]).length}</strong></div></div><div class="roster-tools"><label for="team-player-filter"><b>Full ${esc(field.label)} roster</b> · ${total} / ${total} ingested</label><input id="team-player-filter" class="search-input" type="search" placeholder="Filter this team by player or electorate"></div><div id="team-roster" class="roster"></div></article>`;
      const list=document.getElementById('team-roster'),filter=document.getElementById('team-player-filter');const drawPlayers=()=>{const q=String(filter?.value||'').trim().toLowerCase(),visible=players.filter(p=>!q||[p.name,p.role,p.division,p.electorate,p.state,p.chamber].some(v=>String(v||'').toLowerCase().includes(q)));list.innerHTML=visible.map(p=>`<div class="player-row"><div><span class="player-label">PLAYER · ${esc(words(p.chamber))}</span><b>${esc(p.name)}</b></div><span>${esc(p.role||'')}${p.electorate?` · ${esc(p.electorate)}`:p.division?` · ${esc(p.division)}`:''}</span></div>`).join('')||'<div class="empty-state">No players match this filter.</div>'};filter?.addEventListener('input',drawPlayers);drawPlayers();history.replaceState(null,'',`${location.pathname}?jurisdiction=${encodeURIComponent(field.id)}&team=${encodeURIComponent(party.party_id)}`)};
    jurisdiction.addEventListener('change',populateTeams);select.addEventListener('change',render);populateTeams();
    const meta=document.getElementById('roster-meta'),progress=competitions.ingestion_progress||{};if(meta)meta.textContent=`${226+(progress.state_territory_players_ingested||0)} parliamentary players ingested across Federal Finals and all ${progress.state_territory_jurisdictions_with_complete_current_player_rosters||0} state/territory competitions · current parliamentary roster layer complete · ${sa.snapshot_id}`;
  }catch(err){view.innerHTML='<div class="empty-state"><b>Team rosters unavailable</b><p>The current competition roster runtime could not be loaded into this page.</p></div>'}
}
loadTeamIntelligence();
